export interface CountryInfo {
  name: string;
  code: string;
  flag: string;
  cities: string[];
}

export const COUNTRIES_DATA: CountryInfo[] = [
  {
    name: "India",
    code: "+91",
    flag: "🇮🇳",
    cities: [
      "Delhi",
      "Mumbai",
      "Bengaluru",
      "Hyderabad",
      "Chennai",
      "Kolkata",
      "Lucknow",
      "Pune",
      "Ahmedabad",
      "Srinagar",
      "Jaipur",
      "Bhopal",
      "Patna",
      "Chandigarh",
      "Aligarh",
      "Calicut",
      "Kochi",
      "Kanpur",
      "Nagpur",
      "Indore",
      "Varanasi",
      "Agra",
      "Surat",
      "Meerut",
    ],
  },
  {
    name: "United Arab Emirates",
    code: "+971",
    flag: "🇦🇪",
    cities: [
      "Dubai",
      "Abu Dhabi",
      "Sharjah",
      "Ajman",
      "Ras Al Khaimah",
      "Fujairah",
      "Al Ain",
      "Umm Al Quwain",
    ],
  },
  {
    name: "Saudi Arabia",
    code: "+966",
    flag: "🇸🇦",
    cities: [
      "Riyadh",
      "Jeddah",
      "Mecca",
      "Medina",
      "Dammam",
      "Khobar",
      "Dhahran",
      "Tabuk",
      "Taif",
      "Jubail",
      "Abha",
      "Yanbu",
    ],
  },
  {
    name: "United Kingdom",
    code: "+44",
    flag: "🇬🇧",
    cities: [
      "London",
      "Birmingham",
      "Manchester",
      "Leeds",
      "Glasgow",
      "Bradford",
      "Leicester",
      "Luton",
      "Cardiff",
      "Sheffield",
      "Bristol",
      "Coventry",
      "Slough",
      "Blackburn",
    ],
  },
  {
    name: "United States",
    code: "+1",
    flag: "🇺🇸",
    cities: [
      "New York",
      "Chicago",
      "Houston",
      "Dallas",
      "Los Angeles",
      "Atlanta",
      "Detroit",
      "Washington D.C.",
      "Philadelphia",
      "San Francisco",
      "Boston",
      "Seattle",
      "Austin",
      "Minneapolis",
      "Orlando",
    ],
  },
  {
    name: "Canada",
    code: "+1",
    flag: "🇨🇦",
    cities: [
      "Toronto",
      "Mississauga",
      "Calgary",
      "Vancouver",
      "Ottawa",
      "Montreal",
      "Edmonton",
      "Brampton",
      "Hamilton",
      "Winnipeg",
    ],
  },
  {
    name: "Qatar",
    code: "+974",
    flag: "🇶🇦",
    cities: [
      "Doha",
      "Al Rayyan",
      "Al Wakrah",
      "Al Khor",
      "Umm Salal",
      "Lusail",
      "Al Daayen",
    ],
  },
  {
    name: "Kuwait",
    code: "+965",
    flag: "🇰🇼",
    cities: [
      "Kuwait City",
      "Hawalli",
      "Salmiya",
      "Al Ahmadi",
      "Farwaniya",
      "Jahra",
      "Fahaheel",
      "Sabah Al Salem",
    ],
  },
  {
    name: "Oman",
    code: "+968",
    flag: "🇴🇲",
    cities: [
      "Muscat",
      "Salalah",
      "Seeb",
      "Sohar",
      "Nizwa",
      "Barka",
      "Sur",
      "Ibri",
    ],
  },
  {
    name: "Bahrain",
    code: "+973",
    flag: "🇧🇭",
    cities: [
      "Manama",
      "Riffa",
      "Muharraq",
      "Hamad Town",
      "A'ali",
      "Isa Town",
      "Budaiya",
    ],
  },
  {
    name: "Pakistan",
    code: "+92",
    flag: "🇵🇰",
    cities: [
      "Karachi",
      "Lahore",
      "Islamabad",
      "Rawalpindi",
      "Faisalabad",
      "Peshawar",
      "Multan",
      "Gujranwala",
      "Quetta",
      "Sialkot",
      "Hyderabad",
    ],
  },
  {
    name: "Bangladesh",
    code: "+880",
    flag: "🇧🇩",
    cities: [
      "Dhaka",
      "Chittagong",
      "Sylhet",
      "Rajshahi",
      "Khulna",
      "Comilla",
      "Barisal",
      "Mymensingh",
    ],
  },
  {
    name: "Malaysia",
    code: "+60",
    flag: "🇲🇾",
    cities: [
      "Kuala Lumpur",
      "Penang",
      "Johor Bahru",
      "Shah Alam",
      "Malacca",
      "Petaling Jaya",
      "Ipoh",
      "Cyberjaya",
    ],
  },
  {
    name: "Singapore",
    code: "+65",
    flag: "🇸🇬",
    cities: ["Singapore"],
  },
  {
    name: "Australia",
    code: "+61",
    flag: "🇦🇺",
    cities: [
      "Sydney",
      "Melbourne",
      "Brisbane",
      "Perth",
      "Adelaide",
      "Canberra",
      "Gold Coast",
      "Hobart",
    ],
  },
  {
    name: "Germany",
    code: "+49",
    flag: "🇩🇪",
    cities: [
      "Berlin",
      "Munich",
      "Frankfurt",
      "Hamburg",
      "Cologne",
      "Düsseldorf",
      "Stuttgart",
      "Bonn",
    ],
  },
  {
    name: "South Africa",
    code: "+27",
    flag: "🇿🇦",
    cities: [
      "Johannesburg",
      "Cape Town",
      "Durban",
      "Pretoria",
      "Port Elizabeth",
    ],
  },
  {
    name: "New Zealand",
    code: "+64",
    flag: "🇳🇿",
    cities: ["Auckland", "Wellington", "Christchurch", "Hamilton"],
  },
  {
    name: "Turkey",
    code: "+90",
    flag: "🇹🇷",
    cities: ["Istanbul", "Ankara", "Izmir", "Bursa", "Antalya", "Konya"],
  },
  {
    name: "Egypt",
    code: "+20",
    flag: "🇪🇬",
    cities: ["Cairo", "Alexandria", "Giza", "Shubra El Kheima", "Port Said"],
  },
  {
    name: "Jordan",
    code: "+962",
    flag: "🇯🇴",
    cities: ["Amman", "Zarqa", "Irbid", "Aqaba"],
  },
  {
    name: "Ireland",
    code: "+353",
    flag: "🇮🇪",
    cities: ["Dublin", "Cork", "Galway", "Limerick"],
  },
];
